theme: jekyll-theme-cayman
root: "weiroc.github.io/myblog"
paginate: 3
baseurl: "myblog/"
url: " "
lsi: false
safe: true
source: https://github.com/weiroc/myblog
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

