

paginate: 3
path: /myblog
baseurl: /myblog
url: " "
lsi: false
safe: true

incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

